name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  ci:
    strategy:
      matrix:
        ruby: [3.1.0]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: couchdbshardutils-${{ matrix.image }}-${{ hashFiles('Gemfile.lock') }}
      - name: Install dependencies
        run: bundle install --path vendor/bundle
      - name: Run tests
        run: bundle exec rake spec
      - name: Rubocop
        run: bundle exec rubocop
      - name: Log in to the Container registry
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
